# Generated by Django 5.1.4 on 2025-01-10 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=10)),
                ('date_of_birth', models.DateField()),
                ('state', models.CharField(max_length=50)),
                ('district', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.CharField(max_length=255)),
                ('pincode', models.CharField(max_length=6)),
                ('prefCommlangauge', models.CharField(max_length=10)),
                ('mobile', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=100)),
                ('captcha', models.CharField(max_length=10)),
            ],
        ),
    ]
